feat: support kylin V10
Signed-off-by: Qi Zhang <smallqi1@163.com>

diff --git a/script/init_node b/script/init_node
--- a/script/init_node
+++ b/script/init_node
@@ -45,7 +45,7 @@ function add_user() {
         echo -e "${GREEN}[INFO] User $user already exists ${NC}"
     else
         case $os_type in
-        centos|redhat|euleros|fusionos|anolis)
+        centos|redhat|euleros|fusionos|anolis|kylin)
             add_user_in_redhat "$user" "$pass"
             echo -e "${GREEN}[INFO] User $user has been created ${NC}"
         ;;
@@ -123,7 +123,7 @@ function time_sync() {
 
     echo -e "${GREEN}[INFO] Start time synchronization ${NC}"
     case $os_type in
-    centos|redhat|euleros|fusionos|anolis)
+    centos|redhat|euleros|fusionos|anolis|kylin)
         if [ "$os_version_id" == "8" ]; then
             echo -e "${YELLOW}[WARN] $os_type $os_version_id please manually synchronize the time ${NC}"
         else
@@ -173,6 +173,11 @@ function check_os() {
         echo -e "${RED}[ERROR] Centos or redhat version must be higher than 7.0 ${NC}" && exit 1
     fi
     ;;
+    kylin)
+    if [ "$os_version" != "V10" ]; then
+        echo -e "${RED}[ERROR] Kylin version only V10 is supported ${NC}" && exit 1
+    fi
+    ;;
     ubuntu)
     if [ "$os_version" -lt "1604" ]; then
         echo -e "${RED}[ERROR] Ubuntu version must be higher than 16.04 ${NC}" && exit 1
@@ -198,7 +203,7 @@ function check_kernel() {
 
 function install_nfscli(){
     case $os_type in
-    centos|redhat|euleros|fusionos|anolis)
+    centos|redhat|euleros|fusionos|anolis|kylin)
         sudo yum list installed nfs-utils | grep nfs || sudo yum install -y nfs-utils
         echo -e "${GREEN}[INFO] nfs-utils has been installed ${NC}"
     ;;
